# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15Wg6C827Oy9grlt5-eEgQ0wQFdTeFZAK
"""

import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart

EMAIL_SENDER = "manojsrivatsn@gmail.com"  # Replace with your Gmail
EMAIL_PASSWORD = "biyj kslb ondw vxal"   # Replace with your App Password

def send_email(to_email, weather_info, city):
    subject = f"🌤️ Daily Weather Update - {city}"
    body = f"""Hello,

Here is your daily weather update for {city}:

{weather_info}

Stay prepared,
Your Weather Bot 🌦️
"""

    msg = MIMEMultipart()
    msg["From"] = EMAIL_SENDER
    msg["To"] = to_email
    msg["Subject"] = subject
    msg.attach(MIMEText(body, "plain"))

    try:
        with smtplib.SMTP("smtp.gmail.com", 587) as server:
            server.starttls()
            server.login(EMAIL_SENDER, EMAIL_PASSWORD)
            server.sendmail(EMAIL_SENDER, to_email, msg.as_string())
        print(f"✅ Email sent to {to_email}")
    except Exception as e:
        print(f"❌ Failed to send email to {to_email}:", e)