# -*- coding: utf-8 -*-
"""weather.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/159WQqUekFHRp-9evYeRK6EXl5KkDOmIk
"""

weather_code = """
import requests
import json

API_KEY = "O3Y0uuV95WXcPA7x5QsYwgm0RruivSxm"

def get_weather(location_coords):
    '''
    location_coords: string in format "lat,lon"
    returns: formatted weather string for email
    '''
    url = f"https://api.tomorrow.io/v4/weather/realtime?location={location_coords}&apikey={API_KEY}"

    try:
        response = requests.get(url)
        response.raise_for_status()
        data = response.json()
        values = data.get("data", {}).get("values", {})

        report = (
            f"Temperature: {values.get('temperature')}°C\\n"
            f"Humidity: {values.get('humidity')}%\\n"
            f"Wind Speed: {values.get('windSpeed')} m/s\\n"
            f"Cloud Cover: {values.get('cloudCover')}%\\n"
            f"Precipitation: {values.get('precipitationIntensity')} mm/hr"
        )
        return report
    except Exception as e:
        return f"❌ Failed to fetch weather: {str(e)}"
"""

# Fix formatting before writing
#weather_code = weather_code.replace("\\n", "\n")

with open("weather.py", "w") as f:
    f.write(weather_code)

