# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nlKPhyv71eIBGQphjj46Bm2TlvBXbwtl
"""

import requests
import json

API_KEY = "O3Y0uuV95WXcPA7x5QsYwgm0RruivSxm"

def get_weather(location_coords):
    '''
    location_coords: string in format "lat,lon"
    returns: formatted weather string for email
    '''
    url = f"https://api.tomorrow.io/v4/weather/realtime?location={location_coords}&apikey={API_KEY}"

    try:
        response = requests.get(url)
        response.raise_for_status()
        data = response.json()
        values = data.get("data", {}).get("values", {})

        report_lines = [f"{key}: {val}" for key, val in values.items()]
        report = "\n".join(report_lines)
        return report
        
    except Exception as e:
        return f"❌ Failed to fetch weather: {str(e)}"
